apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-critical
  namespace: monitoring
spec:
  hard:
    cpu: "1000"
    memory: 4Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["system-cluster-critical", "system-node-critical"]